FROM query-rewrite-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .

# CMD from base Dockerfile
WORKDIR /home/user/comps/query_rewrite
CMD ["python", "opea_query_rewrite_microservice.py"]
