---
dockerfile: "Dockerfile"
docker_context: "./../../"
dependencies:
   - pip-manual
   - apt
base-image:
  override:
    - vault.habana.ai/gaudi-docker/1.23.0/ubuntu24.04/habanalabs/pytorch-installer-2.9.0:latest
apt:
  base-image-override: vault.habana.ai/gaudi-docker/1.23.0/ubuntu24.04/habanalabs/pytorch-installer-2.9.0:latest
pip-manual:
  packages:
    - git/vllm-project/vllm-gaudi
# git/vllm-project/vllm-gaudi / requirements.txt
    - ray
    - pandas
    - numba
    - numpy
    - transformers
    - kaldi-native-fbank
    - git/vllm-project/vllm
# git/vllm-project/vllm / requirements/build.txt
    - cmake
    - ninja
    - packaging
    - setuptools
    - setuptools-scm
    - torch
    - wheel
    - jinja2
    - regex
    - build
    - protobuf
# sec updates
    - urllib3
    - jaraco.context
    - wheel
    - xgrammar
