// Copyright (C) 2024-2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

import { createApi, fakeBaseQuery } from "@reduxjs/toolkit/query/react";

import {
  SummarizeFileRequest,
  SummarizePlainTextRequest,
  SummarizeResponse,
} from "@/types/api";

const summarizedResponseText = `This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.This is a simulated summary of the provided content. In a real application, this text would be generated by an AI model based on the input text or file.
The summary aims to capture the main points and essence of the original content in a concise manner.
Furthermore, the summary provides additional context, highlights key arguments, and presents supporting evidence found within the source material.
By distilling complex information into a more digestible format, it enables users to quickly grasp the essential ideas without reading the entire document.
This extended summary is intentionally verbose to ensure it exceeds the typical length of a text element, thereby demonstrating how overflow scenarios can be handled in the user interface.
The summary continues with further elaboration, emphasizing the importance of clarity, relevance, and completeness in effective communication.
Ultimately, the goal is to facilitate understanding and decision-making by presenting the most pertinent information in a structured and accessible manner, even when the original content is lengthy or intricate.
`;

export const summarizationApi = createApi({
  reducerPath: "api",
  baseQuery: fakeBaseQuery(),
  endpoints: (builder) => ({
    summarizePlainText: builder.mutation<
      SummarizeResponse,
      SummarizePlainTextRequest
    >({
      queryFn: async ({ text }) => {
        // Simulate network delay
        await new Promise((resolve) => setTimeout(resolve, 3000));
        console.log("Simulated API call with text:", text);
        // Simulate response
        return { data: { summary: summarizedResponseText } };
      },
    }),
    summarizeFile: builder.mutation<SummarizeResponse, SummarizeFileRequest>({
      queryFn: async ({ file }) => {
        // Simulate network delay
        await new Promise((resolve) => setTimeout(resolve, 3000));
        console.log("Simulated API call with file:", file.name);
        // Simulate response
        return { data: { summary: summarizedResponseText } };
      },
    }),
  }),
});

export const { useSummarizePlainTextMutation, useSummarizeFileMutation } =
  summarizationApi;
