FROM enhanced-dataprep-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY app/uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/app
ENTRYPOINT ["./entrypoint.sh"]
