{
 "title": "EnterpriseRAG / Services / EDP",
 "tags": [
  "entrag",
  "edp"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingested Files & Links",
   "type": "stat",
   "description": "The total volume of ingested files and links available as the knowledge base for the RAG system",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"edp_(files|links)_ingested_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Process",
   "type": "stat",
   "description": "The current number of files and links that are in the process of being ingested.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"edp_(files|links)_(uploaded|processing|dataprep|embedding)_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Chunks",
   "type": "stat",
   "description": "This data indicates the total number of chunks extracted from ingested files and links.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "edp_chunks_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The number of files and links that have encountered error statuses.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"edp_(files|links)_error_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Marked for Deletion",
   "type": "stat",
   "description": "The number of files and links that have been marked for deletion and are undergoing the removal process.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"edp_(files|links)_(canceled|deleting|for_deletion)_total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Number of Files & Links",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "edp_files_total", "legendFormat": "Total Files" },
    { "expr": "edp_links_total", "legendFormat": "Total Links" }
   ]
  },
  {
   "title": "Celery Tasks Status Overview",
   "type": "timeseries",
   "description": "Tracks Celery task states: \n - 'Active Tasks' are tasks currently being processed\n - 'Reserved Tasks' are tasks that have been prefetched by the worker and are waiting to be executed\n - 'Scheduled Tasks' are tasks reserved by the worker with an eta or countdown argument set",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "edp_celery_active_tasks_total", "legendFormat": "Active Tasks" },
    {
     "expr": "edp_celery_reserved_tasks_total",
     "legendFormat": "Reserved Tasks"
    },
    {
     "expr": "edp_celery_scheduled_tasks_total",
     "legendFormat": "Scheduled Tasks"
    }
   ]
  },
  {
   "title": "Total Number of Chunks for Files & Links",
   "type": "timeseries",
   "description": "This data indicates the total number of chunks extracted from ingested files and links.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "edp_files_chunks_total", "legendFormat": "File Chunks" },
    { "expr": "edp_links_chunks_total", "legendFormat": "Link Chunks" },
    { "expr": "edp_chunks_total", "legendFormat": "Total Chunks" }
   ]
  },
  {
   "title": "Files & Links Marked for Deletion",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "edp_files_for_deletion_total", "legendFormat": "Files for Deletion" },
    { "expr": "edp_links_for_deletion_total", "legendFormat": "Links for Deletion" }
   ]
  },
  {
   "title": "Errors & Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Status",
     "type": "timeseries",
     "description": "The count of files and links that encountered error statuses.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      { "expr": "edp_files_error_total", "legendFormat": "Files Error" },
      { "expr": "edp_links_error_total", "legendFormat": "Links Error" }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "{k8s_container_name=\"edp-dataprep\"} |= ``"
      },
      {
       "expr": "{k8s_container_name=\"edp-embedding\"} |= ``"
      },
      {
       "expr": "{k8s_container_name=\"edp-ingestion\"} |= ``"
      },
      {
       "expr": "{k8s_container_name=\"edp-backend\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Files Stage Tracker",
     "type": "timeseries",
     "description": "Displays the flow of files through various stages from upload to ingestion.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
     "targets": [
      { "expr": "edp_files_uploaded_total", "legendFormat": "Files Uploaded" },
      { "expr": "edp_files_processing_total", "legendFormat": "Files Processing" },
      { "expr": "edp_files_dataprep_total", "legendFormat": "Files Dataprep" },
      { "expr": "edp_files_embedding_total", "legendFormat": "Files Embedding" },
      { "expr": "edp_files_ingested_total", "legendFormat": "Files Ingested" },
      { "expr": "edp_files_deleting_total", "legendFormat": "Files Deleting" },
      { "expr": "edp_files_canceled_total", "legendFormat": "Files Canceled" }
     ]
    },
    {
     "title": "Links Stage Tracker",
     "type": "timeseries",
     "description": "Displays the flow of links through various stages from upload to ingestion.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
     "targets": [
      { "expr": "edp_links_uploaded_total", "legendFormat": "Links Uploaded" },
      { "expr": "edp_links_processing_total", "legendFormat": "Links Processing" },
      { "expr": "edp_links_dataprep_total", "legendFormat": "Links Dataprep" },
      { "expr": "edp_links_embedding_total", "legendFormat": "Links Embedding" },
      { "expr": "edp_links_ingested_total", "legendFormat": "Links Ingested" },
      { "expr": "edp_links_deleting_total", "legendFormat": "Links Deleting" },
      { "expr": "edp_links_canceled_total", "legendFormat": "Links Canceled" }
     ]
    }
   ]
  }
 ]
}