{
 "title": "EnterpriseRAG / Services / Details",
 "tags": [
  "entrag",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_requests_total{namespace=~\"chatqa|dataprep|fingerprint\"},namespace)"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "label_values(http_requests_total{namespace=~\"$namespace\"},container)"
    }
   },
   { "name": "Percentage", "query": "99,95,90,50" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=~\"$container_name\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=~\"$container_name\", namespace=~\"$namespace\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(container, method, handler) (rate(http_requests_total{container=~\"$container_name\", namespace=\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"}[$__rate_interval]))",
     "legendFormat": "{{container}}:{{ method }}{{ handler }}"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(container, status) (rate(http_requests_total{container=~\"$container_name\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{container}}:{{status}}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\", container=~\"$container_name\", namespace=\"$namespace\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Request duration  P$Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$Percentage, rate(http_request_duration_seconds_bucket{container=~\"$container_name\", namespace=\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"}[$__rate_interval])) ",
     "legendFormat": "{{container}}:{{handler}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{handler!=\"none\",container=~\"$container_name\", namespace=\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{container}}:{{ handler }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs (all levels)",
     "type": "logs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "{k8s_container_name=~\"$container_name\"} |= ``",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Logs (only lines with detected error)",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "{k8s_container_name=~\"$container_name\"} | detected_level = `error`",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  }
 ]
}