{
 "title": "EnterpriseRAG / Services / GMConnector (router)",
 "description": "Spanmetrics way of demo application view.",
 "tags": [
  "entrag",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "http_route",
    "label": "Route (as Server)",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_route)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_service_created{namespace=~\"chatqa|dataprep\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service (as Client)",
    "query": {
     "query": "label_values(http_client_duration_milliseconds_count{namespace=~\"$namespace\"},net_peer_name)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "0.50, 0.95, 0.99, 0.999, 0.9999, 0.99999"
   },
   {
    "name": "http_status_code",
    "label": "HTTP status code",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Client services - Throughput and Latencies (filter by \"Service\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Client latencies requests histogram for \"${service}\"",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(increase( http_client_duration_milliseconds_bucket{net_peer_name=~\"$service\", namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3x3 - Service Latency - percentile$percentile",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(http_client_duration_milliseconds_bucket{net_peer_name=~\"$service\", namespace=\"$namespace\"}[$__rate_interval])) by (le,net_peer_name))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (net_peer_name) (rate(http_client_duration_milliseconds_count{net_peer_name=~\"$service\", namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Router Client Latencies Over Range  (status=200 only) by service",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(http_client_duration_milliseconds_sum{net_peer_name=~\"$service\", http_status_code=\"200\", namespace=\"$namespace\"}[$__rate_interval]) / increase(http_client_duration_milliseconds_count{net_peer_name=~\"$service\", http_status_code=\"200\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "LLM Token latencies (GMConnector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "First token latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(increase( llm_first_token_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next token latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(increase( llm_next_token_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All tokens latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(increase( llm_all_token_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Piepeline latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(increase( llm_pipeline_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server services (filter by \"Route\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 }
  },
  {
   "title": "GMConnector responses histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(increase( http_server_duration_milliseconds_bucket{http_route=~\"$http_route\", http_status_code=~\"$http_status_code\", namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 7 Router Server Average Latencies Over Range (only http_status=200)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (http_route) ((increase(http_server_duration_milliseconds_sum{http_route=~\"$http_route\", http_status_code=\"200\", namespace=\"$namespace\", job=\"monitoring/router-service\"}[$__rate_interval]) / increase(http_server_duration_milliseconds_count{http_route=~\"$http_route\", http_status_code=\"200\", namespace=\"$namespace\", job=\"monitoring/router-service\"}[$__rate_interval]) >=0) )",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Router Server Rate Load (code/route) ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (http_route, http_status_code) (rate(http_server_duration_milliseconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "code=[{{http_status_code}}] - {{http_route}}"
    }
   ]
  }
 ]
}