FROM vllm-cpu-ubi-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .

# CMD from base Dockerfile
WORKDIR /workspace
ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]
