# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
nri_device_injector_version: "v0.10.0"

tdx:
  enabled: false
  one_td:
    enabled: false  # incompatible with coco
  coco:
    enabled: false  # incompatible with one_td
    runtime_class_name: kata-qemu-tdx
  attestation:
    enabled: false
    kbs_address: ""
