FROM docsum-ui-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY ../../pnpm-lock.yaml ./pnpm-lock.yaml

# CMD from base Dockerfile
CMD ["nginx", "-g", "daemon off;"]
