{{- if index .Values "qdrant" "enabled" -}}
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-qdrant
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: qdrant
data:
  initialize.sh: |
    #!/bin/sh
    ulimit -n $(ulimit -Hn)
    exec ./entrypoint.sh
  production.yaml: |
    {{- tpl (toYaml .Values.qdrant.config) . | nindent 4 }}
{{- end }}
