{{- if index .Values "qdrant" "enabled" -}}
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qdrant
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: qdrant
spec:
  type: {{ .Values.qdrant.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.qdrant.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
