# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure TDX is enabled when his features are enabled
  ansible.builtin.assert:
    that:
      - not tdx.coco.enabled  # coco can be enabled only if TDX is enabled
      - not tdx.one_td.enabled  # one_td can be enabled only if TDX is enabled
      - not tdx.attestation.enabled  # attestation can be enabled only if TDX is enabled
    fail_msg: "To use TDX features (coco, one_td, attestation), TDX must be enabled in config as well."
  when: not tdx.enabled
  tags:
    - install
    - display-configuration
    - pre-upgrade

- name: Ensure TDX features are compatible
  ansible.builtin.assert:
    that:
      - tdx.coco.enabled or tdx.one_td.enabled  # one of tdx.coco and tdx.one_td must be enabled
      - not (tdx.one_td.enabled and not tdx.coco.enabled)  # both of tdx.coco and tdx.one_td can not be enabled at once
    fail_msg: "Exactly one of tdx.coco and tdx.one_td must be enabled when TDX is enabled."
  when: tdx.enabled
  tags:
    - install
    - display-configuration
    - pre-upgrade

# Load KBS_ADDRESS from config, if not provided read from env
- name: Load KBS_ADDRESS environment variable
  ansible.builtin.set_fact:
    KBS_ADDRESS: "{{ tdx.attestation.kbs_address | default(lookup('ansible.builtin.env', 'KBS_ADDRESS'), true) }}"
  when: tdx.attestation.enabled
  tags:
    - install
    - display-configuration
    - pre-upgrade

- name: Verify if KBS address is provided
  ansible.builtin.assert:
    that:
      - (KBS_ADDRESS | default('') | string | length) > 0  # kbs_address can not be an empty string
    fail_msg: >
      TDX attestation requires kbs_address. Please set the tdx.attestation.kbs_address in config
      or set environment variable `KBS_ADDRESS`.
  when: tdx.attestation.enabled
  tags:
    - install
    - display-configuration
    - pre-upgrade
