{
 "title": "EnterpriseRAG Gaudi Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_nic_port_status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "habanalabs_nic_port_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_device_config",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "habanalabs_device_config", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_ecc_feature_mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "habanalabs_ecc_feature_mode", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "clock_soc_mhz",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    { "expr": "habanalabs_clock_soc_max_mhz", "legendFormat": "__auto" },
    { "expr": "habanalabs_clock_soc_mhz", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    { "expr": "habanalabs_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_memory_used_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      { "expr": "habanalabs_memory_used_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_memory_free_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      { "expr": "habanalabs_memory_free_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_memory_total_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "expr": "habanalabs_memory_total_bytes", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "habanalabs_power_mW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "habanalabs_power_mW", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_power_default_limit_mW",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "habanalabs_power_default_limit_mW",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "habanalabs_energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "habanalabs_energy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_temperature_threshold_slowdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_slowdown",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_temperature_threshold_shutdown",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_shutdown",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_temperature_threshold_memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_memory",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_temperature_threshold_gpu",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_gpu",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_temperature_onchip",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      { "expr": "habanalabs_temperature_onchip", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_temperature_onboard",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      { "expr": "habanalabs_temperature_onboard", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "PCI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_pcie_rx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      { "expr": "habanalabs_pcie_rx", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_pcie_tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      { "expr": "habanalabs_pcie_tx", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_pcie_receive_throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "habanalabs_pcie_receive_throughput",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_pcie_transmit_throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "habanalabs_pcie_transmit_throughput",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_pci_link_speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      { "expr": "habanalabs_pci_link_speed", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_pci_link_width",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      { "expr": "habanalabs_pci_link_width", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_pcie_replay_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      { "expr": "habanalabs_pcie_replay_count", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Pending rows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_pending_rows_with_single_bit_ecc_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "habanalabs_pending_rows_with_single_bit_ecc_errors",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_pending_rows_with_double_bit_ecc_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "habanalabs_pending_rows_with_double_bit_ecc_errors",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "habanalabs_pending_rows_state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "habanalabs_pending_rows_state", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Kube info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_kube_info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      { "expr": "habanalabs_kube_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "process_cpu_seconds_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_open_fds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      { "expr": "process_open_fds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_resident_memory_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_start_time_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      { "expr": "process_start_time_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_virtual_memory_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_virtual_memory_max_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "process_virtual_memory_max_bytes",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Promhttp_metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "promhttp_metric_handler_requests_in_flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "promhttp_metric_handler_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_total",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}