{
 "title": "EnterpriseRAG / Host / Habana Exporter (Gaudi)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(habanalabs_clock_soc_max_mhz,instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(habanalabs_clock_soc_max_mhz,device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device utilization ($instance)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "habanalabs_utilization{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Memory utilization ($instance)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance,device) (habanalabs_memory_used_bytes{instance=~\"$instance\", device=~\"$device\"} / habanalabs_memory_total_bytes{instance=~\"$instance\", device=~\"$device\"})",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Power utilization (current/limit) ($instance)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance, device) (habanalabs_power_mW{instance=~\"$instance\", device=~\"$device\"} / habanalabs_power_default_limit_mW{instance=~\"$instance\", device=~\"$device\"})",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Device utilization ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "habanalabs_utilization{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Used memory ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "habanalabs_memory_used_bytes{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Total memory ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "habanalabs_memory_total_bytes{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Free memory ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "habanalabs_memory_free_bytes{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Device power ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "habanalabs_power_mW{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Device power default limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "habanalabs_power_default_limit_mW{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "rate(habanalabs_energy{instance=~\"$instance\", device=~\"$device\"}[$__rate_interval]) / 1000",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Clock SoC current and max ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "habanalabs_clock_soc_max_mhz{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "Max:{{instance}}/{{Serial}}"
    },
    {
     "expr": "habanalabs_clock_soc_mhz{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "Current:{{instance}}/{{Serial}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "On-chip temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_onchip{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Onboard temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_onboard{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Slowdown threshold temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_threshold_slowdown{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Shutdown threshold temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_threshold_shutdown{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory threshold temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_threshold_memory{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "GPU threshhold temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "habanalabs_temperature_threshold_gpu{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  { "title": "PCI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "habanalabs_pcie_rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "habanalabs_pcie_rx{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "habanalabs_pcie_tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "habanalabs_pcie_tx{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "habanalabs_pcie_receive_throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "habanalabs_pcie_receive_throughput{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "habanalabs_pcie_transmit_throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "habanalabs_pcie_transmit_throughput{instance=~\"$instance\", device=~\"$device\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "habanalabs_pci_link_speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    { "expr": "habanalabs_pci_link_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_pci_link_width",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    { "expr": "habanalabs_pci_link_width", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "habanalabs_pcie_replay_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    { "expr": "habanalabs_pcie_replay_count", "legendFormat": "__auto" }
   ]
  },
  { "title": "Pending rows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "habanalabs_pending_rows_with_single_bit_ecc_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "habanalabs_pending_rows_with_single_bit_ecc_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "habanalabs_pending_rows_with_double_bit_ecc_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "targets": [
    {
     "expr": "habanalabs_pending_rows_with_double_bit_ecc_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "habanalabs_pending_rows_state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    { "expr": "habanalabs_pending_rows_state", "legendFormat": "__auto" }
   ]
  },
  { "title": "Kube info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 } },
  {
   "title": "habanalabs_kube_info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    { "expr": "habanalabs_kube_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter container CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 134 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{endpoint=\"habana-metrics\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Exporter container open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 134 },
     "targets": [
      {
       "expr": "process_open_fds{endpoint=\"habana-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Exporter container resident memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{endpoint=\"habana-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus http metrics server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus http requests in flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{endpoint=\"habana-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus http requests rate (with status)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_requests_total{endpoint=\"habana-metrics\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:status={{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_nic_port_status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "targets": [
      { "expr": "habanalabs_nic_port_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_device_config",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "targets": [
      { "expr": "habanalabs_device_config", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_ecc_feature_mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "habanalabs_ecc_feature_mode", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}