{
 "title": "EnterpriseRAG / ModelServing / TorchServe",
 "tags": [
  "entrag",
  "modelserving"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(Requests2XX{namespace=~\"chatqa|dataprep\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backend Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prediction Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "PredictionTime{namespace=\"$namespace\"}",
     "legendFormat": "{{Hostname}}:{{Level}}/{{ModelName}}"
    }
   ]
  },
  {
   "title": "Handler Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "HandlerTime{namespace=\"$namespace\"}",
     "legendFormat": "{{Hostname}}:{{Level}}/{{ModelName}}"
    }
   ]
  },
  { "title": "Frontend Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ts_queue_latency_microseconds{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{hostname}} Model:{{model_name}}:{{model_version}}"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "QueueTime{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}}"
    }
   ]
  },
  {
   "title": "Inference Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(ts_inference_latency_microseconds{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{hostname}} Model:{{model_name}}:{{model_version}}"
    }
   ]
  },
  {
   "title": "Inference Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 20 },
   "targets": [
    {
     "expr": "rate(ts_inference_requests_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{hostname}} Model:{{model_name}}:{{model_version}}"
    }
   ]
  },
  {
   "title": "Average Latency per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ts_inference_latency_microseconds{namespace=\"$namespace\"}/ts_inference_requests_total{namespace=\"$namespace\"}",
     "legendFormat": "{{hostname}} Model:{{model_name}}:{{model_version}}"
    }
   ]
  },
  {
   "title": "Requests 2XX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(Requests2XX{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Level:{{Level}} {{Hostname}}"
    }
   ]
  },
  {
   "title": "Requests 4XX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(Requests4XX{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Level:{{Level}} {{Hostname}}"
    }
   ]
  },
  {
   "title": "Requests 5XX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(Requests5XX{namespace=\"$namespace\"}[5m])",
     "legendFormat": "Level:{{Level}} {{Hostname}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "CPUUtilization{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}}"
    }
   ]
  },
  {
   "title": "Worker Thread Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WorkerThreadTime{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}}"
    }
   ]
  },
  {
   "title": "Worker Load Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WorkerLoadTime{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} WorkerName:{{WorkerName}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "MemoryUsed{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} "
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "MemoryAvailable{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} "
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "MemoryUtilization{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "DiskUsage{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} "
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "DiskAvailable{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} "
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DiskUtilization{namespace=\"$namespace\"}",
     "legendFormat": "Level:{{Level}} {{Hostname}} "
    }
   ]
  }
 ]
}