{
 "title": "EnterpriseRAG Services and LLM (GMConnector)",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(http_client_duration_milliseconds_count,net_peer_name)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_route)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Server services ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP server GMConnector router requests histogram (by http_route) (status=200 only) ",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase( http_server_duration_milliseconds_bucket{http_route=~\"$http_route\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 7 Router Server Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(increase(http_server_duration_milliseconds_sum{http_route=~\"$http_route\", http_status_code=\"200\"}[$__rate_interval]) / increase(http_server_duration_milliseconds_count{http_route=~\"$http_route\", http_status_code=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "LLM Token latencies (GMConnector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "First token latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase( llm_first_token_latency_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next token latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase( llm_next_token_latency_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All tokens latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase( llm_all_token_latency_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All tokens latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase( llm_pipeline_latency_milliseconds_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Client services - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Client latencies requests histogram (be service)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase( http_client_duration_milliseconds_bucket{net_peer_name=~\"$service\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_milliseconds_bucket{net_peer_name=~\"$service\"}[$__rate_interval])) by (le,net_peer_name))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (net_peer_name) (rate(http_client_duration_milliseconds_count{net_peer_name=~\"$service\"}[$__range])))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Router Client Latencies Over Range  (status=200 only) by service",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(http_client_duration_milliseconds_sum{net_peer_name=~\"$service\", http_status_code=\"200\"}[$__rate_interval]) / increase(http_client_duration_milliseconds_count{net_peer_name=~\"$service\", http_status_code=\"200\"}[$__rate_interval])",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  }
 ]
}