gaudi_min_total_cpu_cores: 48
gaudi_min_total_memory_gb: 128
gaudi_min_total_storage_gb: 500
gaudi_min_gaudi_cards: 8
cpu_min_total_cpu_cores: 60
cpu_min_total_memory_gb: 128
cpu_min_total_storage_gb: 200
