---
dockerfile: "Dockerfile"
docker_context: "../../../../../../"
dependencies:
  - pip-uv
  - apt
  - manual
base-image:
  override:
    - python:3.11-slim-bookworm
apt:
  base-image-override: python:3.11-slim-bookworm
manual:
  packages:
# Added because of manual copy from UV image in Dockerfile
    - name: astral-sh/uv
      origin: github
      license: MIT
