# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest

ENV LANG=en_US.UTF-8
WORKDIR /root
RUN pip install --upgrade-strategy eager optimum[habana]
RUN pip install -v git+https://github.com/HabanaAI/vllm-fork.git@v0.5.3.post1+Gaudi-1.18.0

CMD ["/bin/bash"]
