FROM namespace-status-watcher-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/namespace_status_watcher
CMD ["python", "opea_namespace_status_watcher_microservice.py"]
