"""Add dpguard statistics

Revision ID: 24e6a5da0cb3
Revises: 2ba5aa36fd81
Create Date: 2025-08-26 06:52:12.693543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '24e6a5da0cb3'
down_revision: Union[str, Sequence[str], None] = '2ba5aa36fd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = reflection.Inspector.from_engine(op.get_bind())
    table_names = inspector.get_table_names()

    if 'files' in table_names:
        columns = [col['name'] for col in inspector.get_columns('files')]
        if 'dpguard_start' not in columns:
            op.add_column('files', sa.Column('dpguard_start', sa.DateTime(), nullable=True))
        if 'dpguard_end' not in columns:
            op.add_column('files', sa.Column('dpguard_end', sa.DateTime(), nullable=True))

    if 'links' in table_names:
        columns = [col['name'] for col in inspector.get_columns('links')]
        if 'dpguard_start' not in columns:
            op.add_column('links', sa.Column('dpguard_start', sa.DateTime(), nullable=True))
        if 'dpguard_end' not in columns:
            op.add_column('links', sa.Column('dpguard_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'dpguard_end')
    op.drop_column('links', 'dpguard_start')
    op.drop_column('files', 'dpguard_end')
    op.drop_column('files', 'dpguard_start')
    # ### end Alembic commands ###
