"""Add late chunking columns

Revision ID: 66ff1cf986bd
Revises: eddd003d890c
Create Date: 2025-11-02 17:17:24.960489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ff1cf986bd'
down_revision: Union[str, Sequence[str], None] = 'eddd003d890c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('late_chunking_start', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('late_chunking_end', sa.DateTime(), nullable=True))
    op.add_column('links', sa.Column('late_chunking_start', sa.DateTime(), nullable=True))
    op.add_column('links', sa.Column('late_chunking_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'late_chunking_end')
    op.drop_column('links', 'late_chunking_start')
    op.drop_column('files', 'late_chunking_end')
    op.drop_column('files', 'late_chunking_start')
    # ### end Alembic commands ###
