"""Migrate dataprep to extractor, compressor and splitter

Revision ID: 8ae548f52244
Revises: 24e6a5da0cb3
Create Date: 2025-08-26 06:53:34.713118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '8ae548f52244'
down_revision: Union[str, Sequence[str], None] = '24e6a5da0cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = reflection.Inspector.from_engine(op.get_bind())
    table_names = inspector.get_table_names()

    if 'files' in table_names:
        columns = [col['name'] for col in inspector.get_columns('files')]
        if 'text_extractor_start' not in columns:
            op.add_column('files', sa.Column('text_extractor_start', sa.DateTime(), nullable=True))
        if 'text_extractor_end' not in columns:
            op.add_column('files', sa.Column('text_extractor_end', sa.DateTime(), nullable=True))
        if 'text_compression_start' not in columns:
            op.add_column('files', sa.Column('text_compression_start', sa.DateTime(), nullable=True))
        if 'text_compression_end' not in columns:
            op.add_column('files', sa.Column('text_compression_end', sa.DateTime(), nullable=True))
        if 'text_splitter_start' not in columns:
            op.add_column('files', sa.Column('text_splitter_start', sa.DateTime(), nullable=True))
        if 'text_splitter_end' not in columns:
            op.add_column('files', sa.Column('text_splitter_end', sa.DateTime(), nullable=True))
        if 'dataprep_start' in columns:
            op.drop_column('files', 'dataprep_start')
        if 'dataprep_end' in columns:
            op.drop_column('files', 'dataprep_end')

    if 'links' in table_names:
        columns = [col['name'] for col in inspector.get_columns('links')]
        if 'text_extractor_start' not in columns:
            op.add_column('links', sa.Column('text_extractor_start', sa.DateTime(), nullable=True))
        if 'text_extractor_end' not in columns:
            op.add_column('links', sa.Column('text_extractor_end', sa.DateTime(), nullable=True))
        if 'text_compression_start' not in columns:
            op.add_column('links', sa.Column('text_compression_start', sa.DateTime(), nullable=True))
        if 'text_compression_end' not in columns:
            op.add_column('links', sa.Column('text_compression_end', sa.DateTime(), nullable=True))
        if 'text_splitter_start' not in columns:
            op.add_column('links', sa.Column('text_splitter_start', sa.DateTime(), nullable=True))
        if 'text_splitter_end' not in columns:
            op.add_column('links', sa.Column('text_splitter_end', sa.DateTime(), nullable=True))
        if 'dataprep_start' in columns:
            op.drop_column('links', 'dataprep_start')
        if 'dataprep_end' in columns:
            op.drop_column('links', 'dataprep_end')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('dataprep_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('dataprep_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('links', 'text_splitter_end')
    op.drop_column('links', 'text_splitter_start')
    op.drop_column('links', 'text_compression_end')
    op.drop_column('links', 'text_compression_start')
    op.drop_column('links', 'text_extractor_end')
    op.drop_column('links', 'text_extractor_start')
    op.add_column('files', sa.Column('dataprep_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('dataprep_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('files', 'text_splitter_end')
    op.drop_column('files', 'text_splitter_start')
    op.drop_column('files', 'text_compression_end')
    op.drop_column('files', 'text_compression_start')
    op.drop_column('files', 'text_extractor_end')
    op.drop_column('files', 'text_extractor_start')
    # ### end Alembic commands ###
