"""Add ingestion times

Revision ID: eddd003d890c
Revises: 8ae548f52244
Create Date: 2025-08-26 06:54:22.604132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = 'eddd003d890c'
down_revision: Union[str, Sequence[str], None] = '8ae548f52244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = reflection.Inspector.from_engine(op.get_bind())
    table_names = inspector.get_table_names()

    if 'files' in table_names:
        columns = [col['name'] for col in inspector.get_columns('files')]
        if 'ingestion_start' not in columns:
            op.add_column('files', sa.Column('ingestion_start', sa.DateTime(), nullable=True))
        if 'ingestion_end' not in columns:
            op.add_column('files', sa.Column('ingestion_end', sa.DateTime(), nullable=True))

    if 'links' in table_names:
        columns = [col['name'] for col in inspector.get_columns('links')]
        if 'ingestion_start' not in columns:
            op.add_column('links', sa.Column('ingestion_start', sa.DateTime(), nullable=True))
        if 'ingestion_end' not in columns:
            op.add_column('links', sa.Column('ingestion_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'ingestion_end')
    op.drop_column('links', 'ingestion_start')
    op.drop_column('files', 'ingestion_end')
    op.drop_column('files', 'ingestion_start')
    # ### end Alembic commands ###
