---
dockerfile: "Dockerfile"
docker_context: "../"
dependencies:
  - pip-manual
  - apt
  - manual
pip-manual:
  packages:
    - transformers
    - oneccl_bind_pt
    - torchserve
    - torch-model-archiver
    - packaging
base-image:
  override:
    - python:3.11-slim-trixie
apt:
  base-image-override: python:3.11-slim-trixie
manual:
  packages:
# Added because of manual copy from UV image in Dockerfile
    - name: astral-sh/uv
      origin: github
      license: MIT
