{
 "title": "EnterpriseRAG / Host / Habana Exporter (Gaudi)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(habanalabs_clock_soc_max_mhz,instance)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(habanalabs_clock_soc_max_mhz,device)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(habanalabs_utilization,pod_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(habanalabs_utilization,pod_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Top Habana workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Habana all cards utlization by pod (avg over range)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespaced_pod) (label_join( avg_over_time (habanalabs_utilization{pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}[$__rate_interval]), \"namespaced_pod\", \"/\", \"pod_namespace\",\"pod_name\")) / scalar(sum(habanalabs_device_config*100))",
     "legendFormat": "{{namespaced_pod}}"
    }
   ]
  },
  {
   "title": "Habana all cards utlization by pod (avg over range)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (namespaced_pod) (label_join( avg_over_time (habanalabs_utilization{pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}[$__range]), \"namespaced_pod\", \"/\", \"pod_namespace\",\"pod_name\")) / scalar(sum(habanalabs_device_config*100))",
     "legendFormat": "{{namespaced_pod}}"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Device utilization ($instance for $namespace/$pod)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance,device) (habanalabs_utilization{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Memory utilization ($instance for $namespace/$pod)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance,device) (habanalabs_memory_used_bytes{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"} / habanalabs_memory_total_bytes{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Power utilization (current/limit) ($instance for $namespace/$pod)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance, device) (habanalabs_power_mW{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"} / habanalabs_power_default_limit_mW{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"})",
     "legendFormat": "{{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "Device utilization details (card=$instance pod=$pod/$namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "habanalabs_utilization{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
     "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used memory (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "habanalabs_memory_used_bytes{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Total memory (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "habanalabs_memory_total_bytes{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Free memory (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "habanalabs_memory_free_bytes{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Power details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device power (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "habanalabs_power_mW{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Device power default limit (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "habanalabs_power_default_limit_mW{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Energy (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "joule" } },
     "targets": [
      {
       "expr": "rate(habanalabs_energy{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}[$__rate_interval]) / 1000",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Clock SoC current and max (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "rotmhz" } },
     "targets": [
      {
       "expr": "habanalabs_clock_soc_max_mhz{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "Max:{{instance}}/{{Serial}}"
      },
      {
       "expr": "habanalabs_clock_soc_mhz{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "Current:{{instance}}/{{Serial}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "On-chip temperature (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "habanalabs_temperature_onchip{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Onboard temperature (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "habanalabs_temperature_onboard{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Slowdown threshold temperature (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_slowdown{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Shutdown threshold temperature (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_shutdown{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory threshold temperature (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_memory{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "GPU threshhold temperature (card=$instance pod=$pod/$namespace)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "habanalabs_temperature_threshold_gpu{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PCI RX/TX and throughput details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_pcie_rx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "habanalabs_pcie_rx{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pcie_tx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "targets": [
      {
       "expr": "habanalabs_pcie_tx{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pcie_receive_throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "habanalabs_pcie_receive_throughput{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pcie_transmit_throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "habanalabs_pcie_transmit_throughput{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pci_link_speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "targets": [
      {
       "expr": "habanalabs_pci_link_speed{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pci_link_width",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "targets": [
      {
       "expr": "habanalabs_pci_link_width{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pcie_replay_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "habanalabs_pcie_replay_count{instance=~\"$instance\", device=~\"$device\", pod_name=~\"$pod\", pod_namespace=~\"$namespace\"}",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pending rows details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_pending_rows_with_single_bit_ecc_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "habanalabs_pending_rows_with_single_bit_ecc_errors",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pending_rows_with_double_bit_ecc_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
     "targets": [
      {
       "expr": "habanalabs_pending_rows_with_double_bit_ecc_errors",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    },
    {
     "title": "habanalabs_pending_rows_state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "targets": [
      {
       "expr": "habanalabs_pending_rows_state",
       "legendFormat": "{{instance}}/{{device}} {{pod_namespace}} {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exporter pod kubernetes info status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_kube_info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "targets": [
      { "expr": "habanalabs_kube_info", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Exporter Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exporter container CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{endpoint=\"habana-metrics\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Exporter container open file descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "targets": [
      {
       "expr": "process_open_fds{endpoint=\"habana-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Exporter container resident memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{endpoint=\"habana-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus http metrics server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus http requests in flight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
     "targets": [
      {
       "expr": "promhttp_metric_handler_requests_in_flight{endpoint=\"habana-metrics\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus http requests rate (with status)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
     "targets": [
      {
       "expr": "rate(promhttp_metric_handler_requests_total{endpoint=\"habana-metrics\"}[$__rate_interval])",
       "legendFormat": "{{instance}}:status={{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "habanalabs_nic_port_status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "targets": [
      { "expr": "habanalabs_nic_port_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_device_config",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "targets": [
      { "expr": "habanalabs_device_config", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "habanalabs_ecc_feature_mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "habanalabs_ecc_feature_mode", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}