{
 "title": "EnterpriseRAG / Host / Intel(r) Performance Counter Monitor (CPU/Memory)",
 "tags": [
  "entrag",
  "host"
 ],
 "time": { "from": "now-30m", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(Number_of_sockets,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Notice",
   "type": "text",
   "description": "This dashboard will not work unless you install \"PCM sensor server\" separately. ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is <span style=\"color:yellow\">**experimental preview feature**</span> because it is based on <span style=\"color:yellow\">\"work in progress\"</span> PCM helm chart that needs to installed separately. Please follow instructions from project repository \r\n`/deployment/components/telemetry/helm/README.md#b-pcm-sensor-server---xeon-telemetry` README.md file to\r\n install `pcm-sensor-server`.\r\n\r\n Please note, that this dashboard is not dynamic. It needs to be recreated (as described in documentation above) for platform with different capabilities (Memory Bandwidth PMU access) and topology (e.g. number of sockets)."
   }
  },
  {
   "title": "Socket0 Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "Watt" }
   ],
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "DRAM Joules Consumed"
    },
    {
     "expr": "rate(PP0_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "PP0 Joules Consumed"
    },
    {
     "expr": "rate(PP1_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "PP1 Joules Consumed"
    }
   ]
  },
  {
   "title": "Current Socket0 Energy Consumption (Watt)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "DRAM Joules Consumed"
    },
    {
     "expr": "rate(PP0_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "PP0 Joules Consumed"
    },
    {
     "expr": "rate(PP1_Joules_Consumed{instance=\"$node\", socket=\"0\"}[60s])",
     "legendFormat": "PP1 Joules Consumed"
    }
   ]
  },
  {
   "title": "Socket1 Energy Consumption",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Watt" }
   ],
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "DRAM Joules Consumed"
    },
    {
     "expr": "rate(PP0_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "PP0 Joules Consumed"
    },
    {
     "expr": "rate(PP1_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "PP1 Joules Consumed"
    }
   ]
  },
  {
   "title": "Current Socket1 Energy Consumption (Watt)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Package_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "Package Joules Consumed"
    },
    {
     "expr": "rate(DRAM_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "DRAM Joules Consumed"
    },
    {
     "expr": "rate(PP0_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "PP0 Joules Consumed"
    },
    {
     "expr": "rate(PP1_Joules_Consumed{instance=\"$node\", socket=\"1\"}[60s])",
     "legendFormat": "PP1 Joules Consumed"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576 + rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576 + rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576 + rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576 + rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576 + rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576 + rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", aggregate=\"system\"}[60s])/1048576 + rate(DRAM_Writes{instance=\"$node\", aggregate=\"system\"}[60s])/1048576 + rate(Persistent_Memory_Reads{instance=\"$node\", aggregate=\"system\"}[60s])/1048576 + rate(Persistent_Memory_Writes{instance=\"$node\", aggregate=\"system\"}[60s])/1048576",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Bandwidth (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576 + rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576 + rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576 + rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576 + rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576 + rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576 + rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", aggregate=\"system\"}[60s])/1048576 + rate(DRAM_Writes{instance=\"$node\", aggregate=\"system\"}[60s])/1048576 + rate(Persistent_Memory_Reads{instance=\"$node\", aggregate=\"system\"}[60s])/1048576 + rate(Persistent_Memory_Writes{instance=\"$node\", aggregate=\"system\"}[60s])/1048576",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Socket0 Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    },
    {
     "expr": "rate(CXL_Write_Mem{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "CXL Write Mem"
    },
    {
     "expr": "rate(CXL_Write_Cache{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "CXL Write Cache"
    },
    {
     "expr": "(rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s]))/1048576",
     "legendFormat": "DRAM Total"
    },
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s]))/1048576",
     "legendFormat": "Persistent Memory Total"
    }
   ]
  },
  {
   "title": "Current Socket0 Memory Bandwidth (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    },
    {
     "expr": "rate(CXL_Write_Mem{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "CXL Write Mem"
    },
    {
     "expr": "rate(CXL_Write_Cache{instance=\"$node\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "CXL Write Cache"
    },
    {
     "expr": "(rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s]))/1048576",
     "legendFormat": "DRAM Total"
    },
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s]))/1048576",
     "legendFormat": "Persistent Memory Total"
    }
   ]
  },
  {
   "title": "Socket1 Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    },
    {
     "expr": "rate(CXL_Write_Mem{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "CXL Write Mem"
    },
    {
     "expr": "rate(CXL_Write_Cache{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "CXL Write Cache"
    },
    {
     "expr": "(rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s]))/1048576",
     "legendFormat": "DRAM Total"
    },
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s]))/1048576",
     "legendFormat": "Persistent Memory Total"
    }
   ]
  },
  {
   "title": "Current Socket1 Memory Bandwidth (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "DRAM Reads"
    },
    {
     "expr": "rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "DRAM Writes"
    },
    {
     "expr": "rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Reads"
    },
    {
     "expr": "rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "Persistent Memory Writes"
    },
    {
     "expr": "rate(CXL_Write_Mem{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "CXL Write Mem"
    },
    {
     "expr": "rate(CXL_Write_Cache{instance=\"$node\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "CXL Write Cache"
    },
    {
     "expr": "(rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s]))/1048576",
     "legendFormat": "DRAM Total"
    },
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s]))/1048576",
     "legendFormat": "Persistent Memory Total"
    }
   ]
  },
  {
   "title": "PMEM/DRAM Bandwidth Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "PMEM/DRAM" }
   ],
   "targets": [
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s]))/(rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s]))",
     "legendFormat": "Socket0"
    },
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s]))/(rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s]))",
     "legendFormat": "Socket1"
    }
   ]
  },
  {
   "title": "PMEM/DRAM Bandwidth Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"0\"}[60s]))/(rate(DRAM_Writes{instance=\"$node\", socket=\"0\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"0\"}[60s]))",
     "legendFormat": "Socket0"
    },
    {
     "expr": "(rate(Persistent_Memory_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(Persistent_Memory_Reads{instance=\"$node\", socket=\"1\"}[60s]))/(rate(DRAM_Writes{instance=\"$node\", socket=\"1\"}[60s])+rate(DRAM_Reads{instance=\"$node\", socket=\"1\"}[60s]))",
     "legendFormat": "Socket1"
    }
   ]
  },
  {
   "title": "Socket0 UPI Utilization Outgoing Data And Non-Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Utilization Outgoing Data And Non-Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket1 UPI Utilization Outgoing Data And Non-Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Utilization Outgoing Data And Non-Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket0 UPI Utilization Incoming Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Utilization Incoming Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket1 UPI Utilization Incoming Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Utilization Incoming Data Traffic (%)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Utilization_Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])*100",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket0 UPI Outgoing Data And Non-Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Outgoing Data And Non-Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket1 UPI Outgoing Data And Non-Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Outgoing Data And Non-Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 60 },
   "targets": [
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Outgoing_Data_And_Non_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket0 UPI Incoming Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket0 UPI Incoming Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 65 },
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"0\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Socket1 UPI Incoming Data Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "none", "label": "MByte/sec" }
   ],
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Current Socket1 UPI Incoming Data Traffic (MByte/sec)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 70 },
   "targets": [
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_0{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI0"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_1{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI1"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_2{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI2"
    },
    {
     "expr": "rate(Incoming_Data_Traffic_On_Link_3{instance=\"$node\", aggregate=\"system\", socket=\"1\"}[60s])/1048576",
     "legendFormat": "UPI3"
    }
   ]
  },
  {
   "title": "Core C-state residency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "none", "label": "stacked %" }
   ],
   "targets": [
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"0\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C0"
    },
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"0\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])) ",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Current Core C-state residency (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 75 },
   "targets": [
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"0\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C0"
    },
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"0\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])) ",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"core\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Package C-state residency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "none", "label": "stacked %" }
   ],
   "targets": [
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"1\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])) ",
     "legendFormat": "C0"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"1\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Current Package C-state residency (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 82 },
   "targets": [
    {
     "expr": "100 - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"1\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s]))  - (100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])) ",
     "legendFormat": "C0"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"1\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C1"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"2\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C2"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"3\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C3"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"4\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C4"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"5\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C5"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"6\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C6"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"7\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C7"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"8\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C8"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"9\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C9"
    },
    {
     "expr": "100 * rate(RawCStateResidency{ instance=\"$node\", aggregate = \"system\", index = \"10\", source = \"uncore\" }[60s]) / ignoring(source, index) rate(Invariant_TSC{ instance=\"$node\", aggregate = \"system\" }[60s])",
     "legendFormat": "C10"
    }
   ]
  },
  {
   "title": "Instructions Per Cycle",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none", "label": "IPC" }
   ],
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instructions Per Cycle",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 89 },
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Frequency Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "none", "label": "AFREQ" }
   ],
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Clock_Unhalted_Ref{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Clock_Unhalted_Ref{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Clock_Unhalted_Ref{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Frequency Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 94 },
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Clock_Unhalted_Ref{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Clock_Unhalted_Ref{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Clock_Unhalted_Ref{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses Per Instruction",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "none", "label": "L3 MPI" }
   ],
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses Per Instruction",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 99 },
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses Per Instruction",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none", "label": "L2 MPI" }
   ],
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses Per Instruction",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 104 },
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instructions Retired Any",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instructions Retired Any (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 109 },
   "targets": [
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Instructions_Retired_Any{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Clock Unhalted Thread",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Clock Unhalted Thread (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 114 },
   "targets": [
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(Clock_Unhalted_Thread{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L2_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Hits{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Hits (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 119 },
   "targets": [
    {
     "expr": "rate(L2_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Hits{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L2 Cache Misses (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 124 },
   "targets": [
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L2_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L3_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Hits{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Hits (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 129 },
   "targets": [
    {
     "expr": "rate(L3_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Hits{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Hits{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "none", "label": "Million" }
   ],
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L3 Cache Misses (Million)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 134 },
   "targets": [
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"0\"}[60s])/1000000",
     "legendFormat": "Socket0"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"socket\", socket=\"1\"}[60s])/1000000",
     "legendFormat": "Socket1"
    },
    {
     "expr": "rate(L3_Cache_Misses{instance=\"$node\", aggregate=\"system\"}[60s])/1000000",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}