{
 "title": "EnterpriseRAG / Services / Details",
 "tags": [
  "entrag",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_requests_total{namespace=~\"chatqa|edp|fingerprint|chat-history|docsum|audio\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(http_requests_total{namespace=~\"$namespace\"},container)"
    }
   },
   { "name": "Percentage", "query": "99,95,90,50" }
  ]
 },
 "panels": [
  { "title": "System Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU Usage ($container)",
   "type": "stat",
   "description": "Shows the sum of the last observed CPU usage values across selected container(s): $container within the namespace(s): $namespace.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{container=~\"$container\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Shows how much CPU time the service's process is consuming, showing the rate of CPU usage over the past 1 minute for a given service. ",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(process_cpu_seconds_total{container=~\"$container\", namespace=~\"$namespace\"}[1m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Total Memory Usage ($container)",
   "type": "stat",
   "description": "Shows the sum of last observed memory usage across selected container(s): $container within the namespace(s): $namespace.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{container=~\"$container\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Shows the amount of RAM actively used by the the service's processes, excluding swapped-out memory.",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (container) (process_resident_memory_bytes{container=~\"$container\", namespace=~\"$namespace\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "External API Traffic (User-Driven)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Total Requests Per Second",
   "type": "timeseries",
   "description": "Shows the rate of incoming HTTP requests per second.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(container, method, handler) (rate(http_requests_total{container=~\"$container\", namespace=~\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"}[$__rate_interval]))",
     "legendFormat": "{{container}}:{{ method }}{{ handler }}"
    }
   ]
  },
  {
   "title": "Request Duration  P$Percentage",
   "type": "timeseries",
   "description": "This graph shows the estimated $Percentage-th percentile of HTTP request durations. The data is grouped by container, HTTP method, and handler, excluding internal API traffic such as /metrics and  /v1/health_check.\n\nNote: The percentile value is configurable via the `Percentage` variable on the dashboard, allowing dynamic exploration of latency at different thresholds.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.$Percentage, sum by (le, container, method, handler) (rate(http_request_duration_seconds_bucket{container=~\"$container\", namespace=~\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"}[$__rate_interval]))) ",
     "legendFormat": "{{container}}:{{ method }}{{ handler }}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "Shows the average response time for incoming HTTP requests.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container, method, handler) (rate(http_request_duration_seconds_sum{handler!=\"none\",container=~\"$container\", namespace=~\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"}[$__rate_interval]) / rate(http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{container}}:{{ method }}{{ handler }}"
    }
   ]
  },
  {
   "title": "HTTP 5xx Error Rate",
   "type": "timeseries",
   "description": "This metric tracks the rate of HTTP requests with 5xx status codes (server errors) per second, helping identify server-side issues like failures or unavailability.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\", container=~\"$container\", namespace=~\"$namespace\", handler!~\"/metrics|/v1/health_check|none\"}[$__rate_interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Internal API Traffic (Monitoring & Health Checks)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Total Requests Per Second For Monitoring",
   "type": "timeseries",
   "description": "The total number of requests per second for monitoring endpoints `GET /metrics`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(container, method, handler, status) (rate(http_requests_total{container=~\"$container\", namespace=~\"$namespace\", handler=~\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "{{container}}:{{ method }}{{ handler }}:{{status}}"
    }
   ]
  },
  {
   "title": " Total Requests Per Second For Health Check",
   "type": "timeseries",
   "description": "The total number of requests per second for health check endpoints `GET /v1/health_check` ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(container, method, handler, status) (rate(http_requests_total{container=~\"$container\", namespace=~\"$namespace\", handler=~\"/v1/health_check\"}[$__rate_interval]))",
     "legendFormat": "{{container}}:{{ method }}{{ handler }}:{{status}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Logs (all levels)",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "{k8s_container_name=~\"$container\"} |= ``",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Logs (only lines with detected error)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "{k8s_container_name=~\"$container\"} | detected_level = `error`",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}