{{- /*
Copyright (C) 2024-2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/ -}}
{{- range .Values.endpoints }}
{{- if .enabled }}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ printf "%s-route" .name }}
  namespace: {{ .namespace }}
spec:
  ingressClassName: {{ $.Values.ingressClassName }}
  http:
  - name: {{ printf "%s-route" .name }}
    match:
      {{- if $.Values.routeHost }}
      hosts:
        - {{ $.Values.routeHost | quote }}
      {{- end }}
      paths:
      - {{ .path }}
    backends:
      - serviceName: {{ .backend_service }}
        servicePort: {{ .service_port }}
    plugins:
    {{- if .service_regex }}
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri:
          {{- range .service_regex }}
          - {{ . }}
          {{- end }}
    {{- end }}
    - name: limit-count
      enable: true
      config:
        count: {{ .rate_limit_count }}
        time_window: 60
        key_type: var
        key: {{ if .skip_auth }}http_x_mcp_client_id{{ else }}http_authorization{{ end }}
        rejected_code: 429
    {{- if not .skip_auth }}
    - name: authz-keycloak
      enable: true
      config:
        resource_registration_endpoint: {{ $.Values.auth.resource_registration_endpoint }}
        token_endpoint: {{ $.Values.auth.token_endpoint }}
        client_id: {{ $.Values.auth.client_id }}
        policy_enforcement_mode: "ENFORCING"
        ssl_verify: false
        permissions:
          {{- range .permissions }}
          - {{ . }}
          {{- end }}
    {{- end }}
---
{{- end }}
{{- end }}
