# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
edp:
  enabled: true
  namespace: "edp"
  # Path prefixes: set dynamically by solution_config.yaml when routing_mode == "path"
  # Default values used in path mode:
  defaultS3PathPrefix: "/s3"
  defaultSeaweedfsPathPrefix: "/seaweedfs"
  helm:
    version: "{{ helm_version }}"
    chart_name: "edp"
    chart_version: "1.1.0"
    release_name: "edp"
    default_values_file: "{{ playbook_dir }}/../components/edp/values.yaml"
    chart_directory: "{{ playbook_dir }}/../components/edp"

  client_id: "EnterpriseRAG-oidc-minio"

  seaweedfs:
    namespace: "seaweedfs"

  vector_db:
    auth:
      user:
        db_username: default

  redis:
    name: edp-redis
    serviceAccountName: edp-redis-sa

    auth:
      user:
        db_username: default
        password_file_name: "edp-redis-password"

    password:
      secretName: edp-redis-secret

    kubernetesConfig:
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "2000m"
          memory: "2Gi"

    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: "8Gi"
          storageClassName: ""

    redisConfig:
      maxmemory: "2gb"

  postgresql:
    auth:
      admin:
        db_username: admin
        password_file_name: "edp-postgresql-admin-password"
      user:
        db_username: edp
        db_name: edp
        password_file_name: "edp-postgresql-user-password"

  tls:
    secret_name: "tls-secret"

  dpGuard:
    enabled: false

  s3DomainPrefix: "s3"
  uiBrowserDomainPrefix: "seaweedfs"

  storageType: seaweedfs
  minio:
    domainName: "{{ (uiBrowserDomainPrefix | default('seaweedfs')) ~ '.' ~ (FQDN | default('erag.com')) }}"
    apiDomainName: "{{ (s3DomainPrefix | default('s3')) ~ '.' ~ (FQDN | default('erag.com')) }}"
  s3:
    region: "us-east-1"
    accessKeyId: ""
    secretAccessKey: ""
    sqsEventQueueUrl: ""
  s3compatible:
    region: "us-east-1"
    accessKeyId: ""
    secretAccessKey: ""
    internalUrl: "https://s3.example.com"
    externalUrl: "https://s3.example.com"
    edpExternalCertVerify: true
    edpInternalCertVerify: true

  late_chunking:
    # NOTE: If enabled, embedding_model_name must be 'jinaai/jina-embeddings-v2-base-en' for late chunking to work.
    enabled: false

  scheduledSync:
    enabled: false
    syncPeriodSeconds: "60"
    sharepointSyncPeriodSeconds: "60"
