# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: Get namespace for the first pipeline item with type chatqa (falls back to first pipeline namespace)
  ansible.builtin.set_fact:
    chatqa_namespace: >-
      {{
        (pipelines | selectattr('type', 'equalto', 'chatqa') | list | first).namespace
        if (pipelines | selectattr('type', 'equalto', 'chatqa') | list | length > 0)
        else (pipelines | first).namespace
      }}
  tags:
    - install
    - update-configuration
