# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

- name: Create a topology discovery daemonset in default namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: node-topology-debugger
        namespace: default
      spec:
        selector:
          matchLabels:
            app: node-topology-debugger
        template:
          metadata:
            labels:
              app: node-topology-debugger
          spec:
            securityContext:
              fsGroup: 2000
              runAsGroup: 3000
              runAsNonRoot: true
              runAsUser: 1000
              seccompProfile:
                type: RuntimeDefault
            containers:
            - name: debian
              image: debian@sha256:f06537653ac770703bc45b4b113475bd402f451e85223f0f2837acbf89ab020a # debian:bookworm-slim
              command: ["sleep", "infinity"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
            restartPolicy: Always
  tags:
  - install
  - topology-preview
  - update-configuration

- name: Wait for node-topology-debugger pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
    - app=node-topology-debugger
  register: pods_info
  until: pods_info.resources | length > 0 and (pods_info.resources | selectattr('status.phase', 'equalto', 'Running') | list | length) == (pods_info.resources | length)
  retries: 30
  delay: 10
  tags:
  - install
  - topology-preview
  - update-configuration

- name: Initialize cpu_topology_per_node dict
  set_fact:
    cpu_topology_per_node: {}
  tags:
  - install
  - topology-preview
  - update-configuration

- name: Gather CPU/NUMA/AMX info for each node
  include_tasks: get_single_node_topology.yaml
  vars:
    node_name: "{{ item.spec.nodeName }}"
    pod_name: "{{ item.metadata.name }}"
  loop: "{{ pods_info.resources }}"
  loop_control:
    label: "{{ item.spec.nodeName }}"
  tags:
  - install
  - topology-preview
  - update-configuration

- name: Delete node-topology-debugger daemonset
  kubernetes.core.k8s:
    state: absent
    kind: DaemonSet
    name: node-topology-debugger
    namespace: default
  tags:
  - install
  - uninstall
  - topology-preview
  - update-configuration
